## server服务器端口和 session 过期时间的设置
server:
  port: 8080
  servlet:
    session:
      timeout: 10800s

#########  spring 相关的设置   ########
spring:
  ## 热部署
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
  ## freemarker 的配置
  freemarker:
    allow-request-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
  ## 数据源的配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ''
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&
      characterEncoding=utf-8&
      useSSL=false&
      serverTimezone=UTC&
      nullCatalogMeansCurrent=true #不加的话，activiti 26 张表 无法创建
    ## 工作流的配置
    activiti:
      process-definition-location-prefix: classpath*:/processes/
  ## redis的配置
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 200
        min-idle: 200
        max-active: 2000
        max-wait: 1000
    timeout: 3000
  ## 配置静态资源的路径
  resources:
    static-locations: /META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  ## ehcache
  cache:
    type: ehcache
    ehcache:
      config: classpath:/config/ehcache.xml
  ##  rabbitmq 的配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: 'guest'

## 分页插件的配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

## mybatis  的配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  #type-aliases-package: com.yzx.shiro.beans

## shiro 的配置【权限信息的配置】
permission-config:
  perms:
    - url: /com/yzx/admin
      permission: roles[admin]
    - url: /com/yzx/employment
      permission: roles[employment]
    - url: /com/yzx/juese
      permission: perms[juese]
    - url: /com/yzx/yonghu
      permission: perms[yonghu]

## 配置打印 sql 语句
logging:
  level:
    #mybatis 中对应的位置
    com.yzx.shiro.mapper: debug
